from .models import *


__all__ = ["LEVELS"]


LEVELS = [
    Level(
        level_id=1,
        level_name="1-1",
        level_index=0,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                ],
                [
                    CellType.SKIN,
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.METAL,
                    CellType.SKIN,
                ],
                [
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.METAL,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                ],
            ],
            horz_connected=[
                [False, False, True, False, True],
                [True, False, True, False, False],
                [False, True, False, False, False],
            ],
            vert_connected=[
                [False, False, True, True],
                [False, False, False, False],
                [True, True, False, False],
                [False, False, False, False],
            ],
        ),
    ),
    Level(
        level_id=2,
        level_name="1-2",
        level_index=1,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                ],
            ],
            horz_connected=[
                [False, True, True, True, False],
                [False, True, True, True, False],
                [False, False, False, False, False],
            ],
            vert_connected=[
                [False, False, False, False],
                [True, True, True, True],
                [False, False, False, False],
                [False, False, False, False],
            ],
        ),
    ),
    Level(
        level_id=3,
        level_name="1-3",
        level_index=2,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                ],
                [
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.NONE,
                ],
                [
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                ],
            ],
            horz_connected=[
                [False, False, False, False, False],
                [False, False, False, False, False],
                [False, False, False, False, False],
            ],
            vert_connected=[
                [False, False, False, False],
                [True, True, True, False],
                [False, False, False, False],
                [False, False, False, False],
            ],
        ),
    ),
    Level(
        level_id=4,
        level_name="2-1",
        level_index=3,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                    CellType.METAL,
                ],
                [
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                    CellType.METAL,
                ],
                [
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                    CellType.METAL,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                ],
            ],
            horz_connected=[
                [False, True, True, True, False],
                [True, True, True, False, False],
                [False, True, True, False, False],
            ],
            vert_connected=[
                [False, True, True, False],
                [True, True, True, False],
                [True, True, False, False],
                [False, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=5,
        level_name="2-2",
        level_index=4,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.FLESH_FAT,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_FAT,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_FAT,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_FAT,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
            ],
            horz_connected=[
                [False, True, True, True, True],
                [False, True, True, True, True],
                [False, True, True, True, True],
            ],
            vert_connected=[
                [False, True, True, True],
                [False, True, True, True],
                [False, True, True, True],
                [False, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=6,
        level_name="2-3",
        level_index=5,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.BONE_SPINE,
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.BONE_SPINE,
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.BONE_SPINE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
            ],
            horz_connected=[
                [False, True, True, True, False],
                [False, True, True, True, False],
                [True, True, True, True, True],
            ],
            vert_connected=[
                [False, False, False, False],
                [False, False, False, False],
                [False, False, False, False],
                [True, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=7,
        level_name="3-1",
        level_index=6,
        target_state=State(
            cell_types=[
                [
                    CellType.SKIN,
                    CellType.SKIN_HAIR,
                    CellType.SKIN_EYE,
                    CellType.SKIN_HAIR,
                    CellType.SKIN,
                ],
                [
                    CellType.SKIN,
                    CellType.SKIN_HAIR,
                    CellType.METAL,
                    CellType.SKIN_HAIR,
                    CellType.SKIN,
                ],
                [
                    CellType.SKIN,
                    CellType.SKIN_HAIR,
                    CellType.METAL,
                    CellType.SKIN_HAIR,
                    CellType.SKIN,
                ],
                [
                    CellType.SKIN,
                    CellType.SKIN_HAIR,
                    CellType.SKIN,
                    CellType.SKIN_HAIR,
                    CellType.SKIN,
                ],
            ],
            horz_connected=[
                [False, True, False, True, False],
                [False, True, False, True, False],
                [False, True, False, True, False],
            ],
            vert_connected=[
                [True, True, True, True],
                [True, False, False, True],
                [True, False, False, True],
                [True, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=8,
        level_name="3-2",
        level_index=7,
        target_state=State(
            cell_types=[
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.METAL,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.METAL,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                ],
            ],
            horz_connected=[
                [True, True, False, True, True],
                [True, True, False, True, True],
                [True, True, False, False, False],
            ],
            vert_connected=[
                [False, True, True, True],
                [False, False, False, True],
                [False, False, False, True],
                [True, False, False, False],
            ],
        ),
    ),
    Level(
        level_id=11,
        level_name="3-3",
        level_index=8,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                ],
            ],
            horz_connected=[
                [False, False, False, False, False],
                [True, True, True, True, True],
                [False, False, False, False, False],
            ],
            vert_connected=[
                [False, False, False, False],
                [False, False, False, False],
                [False, False, False, False],
                [False, False, False, False],
            ],
        ),
        theoretical_min_waste=2,
    ),
    Level(
        level_id=10,
        level_name="4-1",
        level_index=9,
        target_state=State(
            cell_types=[
                [
                    CellType.SKIN_EYE,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                ],
            ],
            horz_connected=[
                [False, True, True, True, False],
                [False, True, True, True, False],
                [False, True, True, True, False],
            ],
            vert_connected=[
                [True, False, True, False],
                [False, False, False, False],
                [False, False, False, False],
                [False, True, False, True],
            ],
        ),
    ),
    Level(
        level_id=9,
        level_name="4-2",
        level_index=10,
        target_state=State(
            cell_types=[
                [
                    CellType.FLESH_FAT,
                    CellType.FLESH_HEART,
                    CellType.FLESH_FAT,
                    CellType.FLESH_HEART,
                    CellType.FLESH_FAT,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.FLESH_FAT,
                    CellType.FLESH_HEART,
                    CellType.FLESH_FAT,
                    CellType.FLESH_HEART,
                    CellType.FLESH_FAT,
                ],
            ],
            horz_connected=[
                [True, False, False, False, True],
                [True, False, False, False, True],
                [True, False, False, False, True],
            ],
            vert_connected=[
                [True, True, True, True],
                [False, False, False, False],
                [False, False, False, False],
                [True, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=12,
        level_name="4-3",
        level_index=11,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.METAL,
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.NONE,
                    CellType.NONE,
                    CellType.METAL,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                ],
            ],
            horz_connected=[
                [False, False, False, False, False],
                [True, True, False, False, False],
                [True, True, False, False, False],
            ],
            vert_connected=[
                [False, False, False, False],
                [True, True, True, True],
                [True, False, False, False],
                [True, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=13,
        level_name="5-1",
        level_index=12,
        target_state=State(
            cell_types=[
                [
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                ],
                [
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                ],
                [
                    CellType.SKIN_HAIR,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                ],
                [
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.SKIN_EYE,
                    CellType.SKIN_EYE,
                    CellType.SKIN_EYE,
                ],
            ],
            horz_connected=[
                [True, True, False, False, False],
                [True, True, True, True, True],
                [False, True, True, True, True],
            ],
            vert_connected=[
                [True, False, False, False],
                [False, False, False, False],
                [False, False, True, True],
                [False, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=14,
        level_name="5-2",
        level_index=13,
        target_state=State(
            cell_types=[
                [
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.FLESH_HEART,
                    CellType.METAL,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
            ],
            horz_connected=[
                [True, True, True, False, True],
                [True, True, True, False, True],
                [False, False, False, False, True],
            ],
            vert_connected=[
                [False, False, True, True],
                [True, True, False, False],
                [False, False, True, True],
                [True, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=15,
        level_name="5-3",
        level_index=14,
        target_state=State(
            cell_types=[
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
            ],
            horz_connected=[
                [False, True, True, True, True],
                [False, True, False, False, False],
                [False, True, True, True, True],
            ],
            vert_connected=[
                [True, True, True, True],
                [False, False, False, False],
                [False, False, False, False],
                [True, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=17,
        level_name="Bonus 1-1 S. Clark",
        level_index=15,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN_HAIR,
                    CellType.METAL,
                ],
                [
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN_EYE,
                    CellType.SKIN,
                ],
                [
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN_EYE,
                    CellType.SKIN,
                ],
                [
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN_HAIR,
                    CellType.METAL,
                ],
            ],
            horz_connected=[
                [False, False, False, True, False],
                [False, False, False, True, True],
                [False, False, False, True, False],
            ],
            vert_connected=[
                [False, True, True, False],
                [True, True, True, True],
                [True, True, True, True],
                [False, True, True, False],
            ],
        ),
    ),
    Level(
        level_id=18,
        level_name="Bonus 1-2 A. Zuri",
        level_index=16,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                ],
            ],
            horz_connected=[
                [False, False, True, False, False],
                [False, True, False, True, False],
                [True, False, True, False, True],
            ],
            vert_connected=[
                [False, True, True, False],
                [True, False, False, True],
                [False, False, False, False],
                [False, False, False, False],
            ],
        ),
        theoretical_min_waste=3,
    ),
    Level(
        level_id=19,
        level_name="Bonus 1-3 M. Lang",
        level_index=17,
        target_state=State(
            cell_types=[
                [
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.METAL,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                ],
                [
                    CellType.BONE_SPINE,
                    CellType.FLESH_FAT,
                    CellType.FLESH_FAT,
                    CellType.FLESH_FAT,
                    CellType.BONE_SPINE,
                ],
                [
                    CellType.BONE_SPINE,
                    CellType.FLESH_FAT,
                    CellType.FLESH_FAT,
                    CellType.FLESH_FAT,
                    CellType.BONE_SPINE,
                ],
                [
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.METAL,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                ],
            ],
            horz_connected=[
                [True, False, False, False, True],
                [True, True, True, True, True],
                [True, False, False, False, True],
            ],
            vert_connected=[
                [True, False, False, True],
                [False, True, True, False],
                [False, True, True, False],
                [True, False, False, True],
            ],
        ),
        theoretical_min_waste=2,
    ),
    Level(
        level_id=20,
        level_name="Bonus 2-1 E. Hunt",
        level_index=18,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.SKIN_EYE,
                    CellType.SKIN,
                ],
                [
                    CellType.SKIN,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.SKIN,
                ],
                [
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN_EYE,
                    CellType.SKIN,
                ],
                [
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                ],
            ],
            horz_connected=[
                [False, False, False, True, True],
                [True, False, False, True, True],
                [True, True, True, True, True],
            ],
            vert_connected=[
                [False, False, False, True],
                [False, False, False, True],
                [False, False, False, True],
                [True, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=21,
        level_name="Bonus 2-2 I. Wass",
        level_index=19,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.METAL,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.METAL,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
            ],
            horz_connected=[
                [False, True, False, True, False],
                [True, False, True, False, True],
                [False, True, False, False, True],
            ],
            vert_connected=[
                [False, True, True, False],
                [True, False, True, True],
                [True, True, False, False],
                [False, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=22,
        level_name="Bonus 2-3 M. Nauviax",
        level_index=20,
        target_state=State(
            cell_types=[
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.METAL,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.METAL,
                ],
            ],
            horz_connected=[
                [True, True, False, True, True],
                [True, True, False, True, True],
                [False, True, False, True, False],
            ],
            vert_connected=[
                [True, True, True, True],
                [False, False, False, False],
                [True, True, True, True],
                [False, True, True, False],
            ],
        ),
    ),
    Level(
        level_id=23,
        level_name="Bonus 3-1 M. Christensen",
        level_index=21,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.METAL,
                ],
                [
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN_EYE,
                    CellType.SKIN,
                    CellType.SKIN,
                ],
                [
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN_EYE,
                    CellType.SKIN,
                    CellType.SKIN,
                ],
                [
                    CellType.METAL,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.METAL,
                ],
            ],
            horz_connected=[
                [False, True, True, True, False],
                [True, True, True, True, True],
                [False, True, True, True, False],
            ],
            vert_connected=[
                [False, True, True, False],
                [True, True, True, True],
                [True, True, True, True],
                [False, True, True, False],
            ],
        ),
    ),
    Level(
        level_id=24,
        level_name="Bonus 3-2 T. Quinn",
        level_index=22,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.BONE_SPINE,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.BONE_SPINE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
            ],
            horz_connected=[
                [False, False, False, False, True],
                [True, False, False, True, True],
                [True, False, False, False, True],
            ],
            vert_connected=[
                [False, True, True, True],
                [True, True, True, False],
                [False, False, False, False],
                [True, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=25,
        level_name="Bonus 3-3 J. Maddux",
        level_index=23,
        target_state=State(
            cell_types=[
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.METAL,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
                [
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                ],
            ],
            horz_connected=[
                [True, True, True, False, True],
                [True, True, True, False, True],
                [True, True, False, False, True],
            ],
            vert_connected=[
                [True, False, True, True],
                [True, False, False, False],
                [True, False, True, False],
                [True, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=26,
        level_name="Bonus 4-1 J. Sheehan",
        level_index=24,
        target_state=State(
            cell_types=[
                [
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN_EYE,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                ],
                [
                    CellType.SKIN_HAIR,
                    CellType.SKIN_HAIR,
                    CellType.SKIN,
                    CellType.SKIN,
                    CellType.SKIN_EYE,
                ],
            ],
            horz_connected=[
                [False, True, False, False, False],
                [False, False, True, False, False],
                [False, True, False, False, False],
            ],
            vert_connected=[
                [True, True, True, True],
                [False, True, True, False],
                [False, True, True, False],
                [True, True, True, True],
            ],
        ),
    ),
    Level(
        level_id=27,
        level_name="Bonus 4-2 J. Li",
        level_index=25,
        target_state=State(
            cell_types=[
                [
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_HEART,
                    CellType.SEED,
                    CellType.FLESH_HEART,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.FLESH_HEART,
                    CellType.METAL,
                ],
            ],
            horz_connected=[
                [False, False, False, False, False],
                [False, True, False, True, False],
                [False, True, False, True, False],
            ],
            vert_connected=[
                [False, False, False, False],
                [False, True, True, False],
                [False, False, False, False],
                [False, True, True, False],
            ],
        ),
        theoretical_min_waste=1,
    ),
    Level(
        level_id=28,
        level_name="Bonus 4-3 D. Viczian",
        level_index=26,
        target_state=State(
            cell_types=[
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.METAL,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.METAL,
                ],
                [
                    CellType.METAL,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.BONE_SPINE,
                    CellType.METAL,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                ],
            ],
            horz_connected=[
                [False, True, False, True, False],
                [False, True, True, True, False],
                [False, True, False, True, False],
            ],
            vert_connected=[
                [True, False, False, True],
                [False, True, False, False],
                [False, False, True, False],
                [True, False, False, True],
            ],
        ),
    ),
    Level(
        level_id=29,
        level_name="Bonus 5-1 G. Tows",
        level_index=27,
        target_state=State(
            cell_types=[
                [
                    CellType.SKIN,
                    CellType.SKIN_EYE,
                    CellType.SKIN,
                    CellType.SKIN_EYE,
                    CellType.SKIN,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.BONE_SPINE,
                    CellType.METAL,
                    CellType.BONE_SPINE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.BONE_SPINE,
                    CellType.NONE,
                    CellType.BONE_SPINE,
                    CellType.FLESH_MUSCLE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.BONE_SPINE,
                    CellType.NONE,
                    CellType.BONE_SPINE,
                    CellType.FLESH_MUSCLE,
                ],
            ],
            horz_connected=[
                [True, False, False, False, True],
                [True, False, False, False, True],
                [True, False, False, False, True],
            ],
            vert_connected=[
                [True, True, True, True],
                [True, False, False, True],
                [True, False, False, True],
                [True, False, False, True],
            ],
        ),
    ),
    Level(
        level_id=30,
        level_name="Bonus 5-2 A. Katz",
        level_index=28,
        target_state=State(
            cell_types=[
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.BONE,
                    CellType.NONE,
                ],
                [
                    CellType.METAL,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.BONE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.BONE,
                ],
                [
                    CellType.FLESH_MUSCLE,
                    CellType.FLESH_MUSCLE,
                    CellType.BONE,
                    CellType.NONE,
                    CellType.NONE,
                ],
            ],
            horz_connected=[
                [False, True, False, False, False],
                [False, True, False, False, False],
                [True, False, False, False, False],
            ],
            vert_connected=[
                [True, True, True, False],
                [False, True, True, True],
                [True, True, True, True],
                [True, True, False, False],
            ],
        ),
    ),
    Level(
        level_id=16,
        level_name="Puzzle Editor",
        level_index=29,
        target_state=State(
            cell_types=[
                [
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                ],
                [
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                ],
                [
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                ],
                [
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                    CellType.NONE,
                ],
            ],
            horz_connected=[
                [False, False, False, False, False],
                [False, False, False, False, False],
                [False, False, False, False, False],
            ],
            vert_connected=[
                [False, False, False, False],
                [False, False, False, False],
                [False, False, False, False],
                [False, False, False, False],
            ],
        ),
        can_place_metal=True,
    ),
]
assert all(i == level.level_index for i, level in enumerate(LEVELS))
